### PR TITLE
Feature: Add `/schedule and /schedule/{id}` path to openAPI3 definition

### LINKED ISSUE #194: Add endpoint to create `ScheduleConfiguration`
## User stories
As a user I want to reuse Schedule Configuration in order to improve the workflow with the API.

## (Wiki) References
- https://github.com/BP2022-AP1/bp2022-ap1/wiki/REST-API

## Acceptance Criteria
- [x] Add GET `/utils/schedule/` to OpenAPI3 definition
- [x] Add POST `/utils//schedule` to OpenAPI3 definition
- [x] Add PUT `/utils/schedule/:id` to OpenAPI3 definition
- [x] Add GET `/utils/schedule/:id` to OpenAPI3 definition
- [x] Add paths to wiki
- [x] Add issue to implement endpoint for schedule configuration

### PR DESCRIPTION
**Pull request by antonykamp**
Fixes #194 

Add path for creating, deleting, updating a schedule and getting information.

## PR checklist

- [x] Acceptance criteria fulfilled
- [x] Additional features are tested
- [x] Docs (code, wiki & diagrams) updated
- [ ] Dev-branch has been merged into local branch to resolve conflicts
- [ ] Tests and linter have passed AFTER local merge
- [ ] Another dev reviewed and approved

### CODE REVIEW

**Review by CR1337 — COMMENTED** [review]
Is it compatible with #234?
See src/schedule/schedule_configuration.py

**Comment by antonykamp** [comment]
> Is it compatible with https://github.com/BP2022-AP1/bp2022-ap1/pull/234?
> See src/schedule/schedule_configuration.py

Not really 😂 Thanks for pointing out. I'll rethink it.

**Comment by antonykamp** [comment]
I thought about it again 🤔 

I think the schema `Schedule` will inherit from your `ScheduleConfiguration` and I'll add a new array-field `platform`. The implementor will extract the platforms, create a ScheduleConfiguration and then ScheduleConfigurationXSimulationPlatform with the platform array 👍

**Comment by CR1337** [comment]
> I thought about it again thinking
> 
> I think the schema `Schedule` will inherit from your `ScheduleConfiguration` and I'll add a new array-field `platform`. The implementor will extract the platforms, create a ScheduleConfiguration and then ScheduleConfigurationXSimulationPlatform with the platform array +1

That sounds reasonable. Good job :+1: 
I will approve after merging `dev` into this branch :P

**Review by CR1337 — APPROVED** [review]
:+1:

**Pull request merged**
