### PR TITLE
Fix: replace autogenerated lines in OpenAPI3 definition

### LINKED ISSUE #219: OpenAPI definition contains auto generated lines
## Problem Description

Some containers are looks like auto generated lines. Please correct.

### PR DESCRIPTION
**Pull request by antonykamp**
Fixes #219 

Replace auto generated lines with meaningful ones in openAPI3 definition.

## PR checklist

- [x] Acceptance criteria fulfilled
- [x] Additional features are tested
- [ ] Dev-branch has been merged into local branch to resolve conflicts
- [ ] Tests and linter have passed AFTER local merge
- [ ] Another dev reviewed and approved

### CODE REVIEW

**Review by CR1337 — COMMENTED** [review]
Could you explain what the problem here is and how your changes fixed it? 🤔🙂

**Comment by antonykamp** [comment]
> Could you explain what the problem here is and how your changes fixed it? 🤔🙂

Thanks for asking! I'll explain it better next time in the PR description 👍 
I used a tool to generate some components. But apparently, I had some typos 🙃 see: createToken_request

And the generator summarized the response-schemas with only an id into one schema, namely createSimulationConfiguration_201_response. We could consider reintroducing it to minimize code duplication. What do you think? 🤔

**Comment by CR1337** [comment]
> > Could you explain what the problem here is and how your changes fixed it? thinkingslightly_smiling_face
> 
> Thanks for asking! I'll explain it better next time in the PR description +1 I used a tool to generate some components. But apparently, I had some typos upside_down_face see: createToken_request
> 
> And the generator summarized the response-schemas with only an id into one schema, namely createSimulationConfiguration_201_response. We could consider reintroducing it to minimize code duplication. What do you think? thinking

Ah I see. I think your solution is more clear than having those references. I like it. Thanks for changing it :)

**Review by CR1337 — APPROVED** [review]
I like it. Approved :+1:

**Pull request merged**
